spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=demo;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'